services:
  comfyui-default:
    build:
      context: .
      dockerfile: ./instances/default/Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        USERNAME: ${USERNAME}
        CUDA_BASE_IMAGE: nvidia/cuda:13.0.3-cudnn-devel-ubuntu24.04
        PYTHON_VERSION: 3.14.4
    env_file:
      - ./instances/default/instance.env
    user: "${UID}:${GID}"
    working_dir: /ComfyUI
    volumes:
      - ${DEFAULT_COMFY_HOST_PATH:-./ComfyUI}:/ComfyUI
      - default-home-data:/home/${USERNAME}
      - default-temp-data:/temp-data
      - ${MODELS_HOST_PATH:-./ComfyUI/models}:/ComfyUI/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - ${DEFAULT_HOST_PORT:-8188}:8188
    restart: unless-stopped
    networks:
      internal:
networks:
  internal:
volumes:
  default-temp-data:
  default-home-data:
