services:
  comfyui:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.comfyui
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
        USERNAME: ${USERNAME}
    environment:
      - COMFY_COMMANDLINE_SWITCHES=${COMFY_COMMANDLINE_SWITCHES}
    user: "${UID}:${GID}"
    working_dir: /ComfyUI
    volumes:
      - ./ComfyUI:/ComfyUI
      - home-data:/home/${USERNAME}
      - temp-data:/temp-data
      - ${MODELS_HOST_PATH:-"./ComfyUI/models"}:/ComfyUI/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "8188:8188"
    restart: unless-stopped
    networks:
      internal:
  mobile:
    build:
      context: ./.docker
      dockerfile: Dockerfile.comfyui-mini
    networks:
      internal:
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./ComfyUI-mini/config.json:/comfyui-mini/config/default.json
      - ./ComfyUI/output:/output
networks:
  internal:
volumes:
  temp-data:
  home-data:
