FROM node:24-alpine3.21
RUN apk update && apk add git
RUN git clone https://github.com/ImDarkTom/ComfyUIMini.git /comfyui-mini
WORKDIR /comfyui-mini
RUN npm install
RUN npm run build
CMD ["npm", "start"]
